### ISSUE TITLE
10.10 compatibility?

### ISSUE THREAD

**Issue by flammable** [sheagcraig/auto_logout#3]
Hey Shea!  Thanks again for this - it's been essential to have in our labs.

Have you used this on 10.10 at all?  We're doing some testing, and have found the dialog box appears at the specified idle time, but disappears and keeps reappearing.  The machine doesn't reboot.

Is it possible this is something I'm doing on my end?  Anything I can do to help debug, if you're interested in fixing it for your environment?

Thanks!

Mike

**Comment by sheagcraig** [comment]
Mike, that's great to hear that you guys are using it! I haven't tested it on 10.10, since we're stuck in the academic year testing cycle that Apple has forced us into with their fall releases!

I'll add this to my list of things to look into. I have some new methods for dialog boxes and things that may be more portable/future-proof that we could add in and test.

We actually haven't been using it, but I'm thinking I may start again, so this will be good research!

**Comment by flammable** [comment]
That would be awesome, thanks!  Please let me know if there's anything I can do to help.  I don't speak Python, but I have plenty of test machines here.

**Comment by sheagcraig** [comment]
@flammable I'm looking at it today. I installed it on a test machine running 10.10 and the applescript notification and both restart and shutdowns worked.

To be fair, I forced it by editing the script to always assume it was idle, because I don't want to sit around and wait that long!

I then just set the launchagent to run every 3 seconds, and just always assume that it was idle, and it ran automatically as expected, and then restarted.

Unfortunately, since I just imaged it, it grabbed the 10.10.3 update while I was doing something else and now it's stuck at the boot progress thing so I can't do any more testing today.

If you could test again and let me know if you're still seeing issues. I would edit the LaunchAgent StartInterval and autoLogout.py's MAXIDLE and LO_TIMEOUT to something less lengthy so you can quickly assess whether it's working.

I would also check and make sure that the sudo perms were added to /etc/sudoers.

**Comment by flammable** [comment]
Thanks, Shea!  I just tried it with a 10.10.3 machine, and it still doesn't seem to be working for me.

My test machine is in another room, so I've been periodically going back and checking on it (when ARD says the machine is idle for enough time).  The script is set to:

MAXIDLE = 3600
LO_TIMEOUT = 120

I haven't modified the LaunchAgent, just the script.  These worked on 10.9, but I'm wondering if tweaking them might help.  I checked /etc/sudoers, and it the permissions were added properly.

Is there anything else I can check?

**Comment by sheagcraig** [comment]
Hmmm, head scratcher, for sure!

I've got a test machine all primed for this with 10.10.3, so I'll try it again to confirm.

Let me throw a much more chatty version into testing; you can grab it, make a package, and test off of that. It has syslog statements all along the way, so we can figure out exactly where it's failing.

**Comment by sheagcraig** [comment]
Yeah-dropped a new package on a new 10.10.3 machine, logged into the gui and into an ssh session watching the syslog. I edited down the idle time to make it trigger sooner. I got prompted and cancelled (which worked) and then I got prompted again 5 minutes later and let it run; and it restarted perfectly.

Something must be wrong!

**Comment by sheagcraig** [comment]
BTW-I renamed it to auto_logout to get pylint off my back and to be more consistent with my other projects. So existing installations may need to have the old one cleaned.

**Comment by sheagcraig** [comment]
If this still doesn't work, I would try adding in a ton of extra syslog.syslog() statements to see EXACTLY where it's failing. I can doctor one up if you can't figure it out. If you just copy/paste one of the existing ones into different parts (editing the message part in the ""), you could add some in.

I don't see how any other settings would prevent this from working. With the new version, you'll at least be able to see in the system log where different steps are getting run and what happens. Let me know what you see in the system log, and also I guess we could look at ```/etc/sudoers```.

**Comment by flammable** [comment]
Thanks for the help with this!

I'm still having some trouble - pretty stumped at this point.  I've only changed these lines in the script:

```
__version__ = 1.5.1
# Number of seconds to wait before initiating a logout
MAXIDLE = 3600
# Number of seconds user has to cancel logout
LO_TIMEOUT = 120
```

The original script looks like this:

```
__version__ = 1.5.1
# Number of seconds to wait before initiating a logout
MAXIDLE = 1800
# Number of seconds user has to cancel logout
LO_TIMEOUT = 10
```

Here's my ```/etc/sudoers``` file:

```
# sudoers file.
#
# This file MUST be edited with the 'visudo' command as root.
# Failure to use 'visudo' may result in syntax or file permission errors
# that prevent sudo from running.
#
# See the sudoers man page for the details on how to write a sudoers file.
#

# Host alias specification

# User alias specification

# Cmnd alias specification

# Defaults specification
Defaults	env_reset
Defaults	env_keep += "BLOCKSIZE"
Defaults	env_keep += "COLORFGBG COLORTERM"
Defaults	env_keep += "__CF_USER_TEXT_ENCODING"
Defaults	env_keep += "CHARSET LANG LANGUAGE LC_ALL LC_COLLATE LC_CTYPE"
Defaults	env_keep += "LC_MESSAGES LC_MONETARY LC_NUMERIC LC_TIME"
Defaults	env_keep += "LINES COLUMNS"
Defaults	env_keep += "LSCOLORS"
Defaults	env_keep += "SSH_AUTH_SOCK"
Defaults	env_keep += "TZ"
Defaults	env_keep += "DISPLAY XAUTHORIZATION XAUTHORITY"
Defaults	env_keep += "EDITOR VISUAL"
Defaults	env_keep += "HOME MAIL"

# Runas alias specification

# User privilege specification
root	ALL=(ALL) ALL
%admin	ALL=(ALL) ALL

# Uncomment to allow people in group wheel to run all commands
# %wheel	ALL=(ALL) ALL

# Same thing without a password
# %wheel	ALL=(ALL) NOPASSWD: ALL

# Samples
# %users  ALL=/sbin/mount /cdrom,/sbin/umount /cdrom
# %users  localhost=/sbin/shutdown -h now
ALL	ALL=(root) NOPASSWD: /sbin/reboot -q
ALL	ALL=(root) NOPASSWD: /sbin/shutdown -h now
```

The behavior I'm seeing with the new script is that the dialog doesn't appear at all now - and nothing is written to the system log (at least, not by the script itself).  I am seeing these in ```/var/log/system.log``` every 5 minutes upon logging in:

```
Apr 27 18:13:10 msolin-lab com.apple.xpc.launchd[1] (org.da.auto_logout[4891]): Service exited with abnormal code: 1
```

Would adding syslog.syslog() statements help here?  It looks like there's a lot of logging already, where else would you insert those?  I'd love an example file, if you think it'll make a difference. :)

I think my next step is going to be shortening the idle times, too.  I want to be 100% sure that what we deploy to the labs functions correctly, but waiting an hour each time has been tough. ;)

I'll try the script as-is and report back.  Thanks again!

**Comment by flammable** [comment]
Nope, set the values back to the defaults and am still seeing the same error:

```
Apr 27 18:34:17 msolin-lab com.apple.xpc.launchd[1] (org.da.auto_logout[1092]): Service exited with abnormal code: 1
```

**Comment by sheagcraig** [comment]
Hey Mike,
that's definitely an issue with the LaunchAgent. I'm able to recreate it now. Hopefully this will lead to some solutions!

**Comment by sheagcraig** [comment]
Also, the LO_TIMEOUT should be 120, as you set it. I accidentally changed it and committed it! I'll revert it.

**Comment by sheagcraig** [comment]
Ugh. This works on my end again now. The error you reported above was due to an uncaught syntax error in the latest version. I hope that is the only problem, but we'll see. Give it another go, and hopefully it will work, or at least more helpfully report on issues.

**Comment by flammable** [comment]
Thank you so much!  Testing it again now!

**Comment by flammable** [comment]
Got some more data - here's where it seems to fail:

```
Apr 28 12:22:12 msolin-lab auto_logout.py[2500]: System Idle: 1765.172021 seconds out of 1800 allowed.
Apr 28 12:22:12 msolin-lab auto_logout.py[2500]: System is not idle.
Apr 28 12:22:31 msolin-lab LabStatsClient[72]: Detected MAC: 64:b9:e8:c1:a6:94
Apr 28 12:27:12 msolin-lab auto_logout.py[2743]: System Idle: 2065.246765 seconds out of 1800 allowed.
Apr 28 12:27:12 msolin-lab auto_logout.py[2743]: System is idle.
Apr 28 12:27:31 msolin-lab LabStatsClient[72]: Detected MAC: 64:b9:e8:c1:a6:94
Apr 28 12:29:13 msolin-lab auto_logout.py[2743]: Applescript result:  Error: 44:193: execution error: System Events got an error: AppleEvent timed out. (-1712)
Apr 28 12:29:13 msolin-lab auto_logout.py[2743]: User cancelled auto logout.
```

I saw the dialog box pop up, but left it alone - it disappeared by itself, then I checked the logs and saw this.  Is it possible something else we have installed interfered?

**Comment by sheagcraig** [comment]
Geez. I've been staring at this for awhile. And then I noticed it _is_ actually throwing a useful error.
AppleEvent timed out means that out LO_TIMEOUT is too long. That's why I never get it to fail. I've set the LO_TIMEOUT to 10 seconds because I don't want to sit around waiting for it. But lo and behold, set it to 120 and it throws that error.

Try editing the LO_TIMEOUT to something lower and see if it works. I'm sure you could stopwatch it to see what the upper limit is.

Let me know what you find out (I have to run!) and I'll make it the new default. I thought 120 was pretty reasonable, but apparently that's TOO long!

**Comment by flammable** [comment]
Awesome!  That makes complete sense.  I lowered it to 90 seconds and it worked perfectly.

Thanks again, I really appreciate all of the help with this!  In some of our labs, students log in, print their document, then get up and walk away from the machine and never come back.  They'll even leave their email logged in, it's really weird.  This script helps a lot.  Thank you so much!

**Comment by sheagcraig** [comment]
Hey @flammable, just wanted to close out this issue and let you know that with the Cocoa alerts  (rather than applescript), the new version accepts whatever ```LO_TIMEOUT``` value you want; plus adds in icons too which is kind of nice. Thanks for pushing me to update this! I am going to start using it in our labs again!

**Comment by flammable** [comment]
Sweet!  I tested it with 120 seconds, and it works perfectly.  The custom icon is icing on the cake!

Thanks again!
